dbt_project:
  outputs:

    dev:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      port: 5439
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      dbname: dev
      schema: analytics
      threads: 4

    ci:
      type: duckdb
      path: ":memory:"
      schema: analytics
      threads: 1

  target: dev